// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHbUpAjjJwfHFCm5iDt9ZoZR0NHllLKW4',
    appId: '1:389801053746:android:8c982311298978761b762b',
    messagingSenderId: '389801053746',
    projectId: 'cameramarketing-91d5a',
    storageBucket: 'cameramarketing-91d5a.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz7HN1me3Js8XOTeVD7zfTVLI9MUbMc3U',
    appId: '1:389801053746:web:41d0d7c834d2dc1f1b762b',
    messagingSenderId: '389801053746',
    projectId: 'cameramarketing-91d5a',
    authDomain: 'cameramarketing-91d5a.firebaseapp.com',
    storageBucket: 'cameramarketing-91d5a.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUAwO3IWhzVrdFm3xmCv6HB_S_mAbzPNw',
    appId: '1:389801053746:ios:55dbaa2469a681271b762b',
    messagingSenderId: '389801053746',
    projectId: 'cameramarketing-91d5a',
    storageBucket: 'cameramarketing-91d5a.firebasestorage.app',
    iosBundleId: 'com.asyncstudio.cameraMarketingApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUAwO3IWhzVrdFm3xmCv6HB_S_mAbzPNw',
    appId: '1:389801053746:ios:55dbaa2469a681271b762b',
    messagingSenderId: '389801053746',
    projectId: 'cameramarketing-91d5a',
    storageBucket: 'cameramarketing-91d5a.firebasestorage.app',
    iosBundleId: 'com.asyncstudio.cameraMarketingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz7HN1me3Js8XOTeVD7zfTVLI9MUbMc3U',
    appId: '1:389801053746:web:d90cd70eedfe688c1b762b',
    messagingSenderId: '389801053746',
    projectId: 'cameramarketing-91d5a',
    authDomain: 'cameramarketing-91d5a.firebaseapp.com',
    storageBucket: 'cameramarketing-91d5a.firebasestorage.app',
  );

}